name: CI CD

on:
  pull_request:
    branches: [ "develop", "stage", master ]
  push:
    branches: ['task/refact-pipe']

jobs:
  develop:
    name: Develop
    environment:
      name: stage  
      url: https://fernandonas.github.io/pipeline/

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Use Node
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
    - run: npm ci
    - run: npm run build
    - run: npm run test
    - uses: cinotify/github-action@main
      with:
        to: ${{ secrets.NOTIFICATION_EMAIL }}
        subject: 'Pipeline'
        body: 'Notificação de pipeline'
  github-pages:
    name: Production
    environment:
      name: github-pages
      url: https://fernandonas.github.io/pipeline/
    needs: [develop]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Download build
        uses: actions/download-artifact@v1
        with:
          name: deploy_dist
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: deploy_dist/pipeline

